name: WaterReminderApp
options:
  bundleIdPrefix: com.whio
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  groupSortPosition: 0
  generateEmptyDirectories: false
  createIntermediateGroups: false

targets:
  WaterReminderApp:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Sources
      - path: Assets.xcassets
    settings:
      INFOPLIST_FILE: Sources/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.whio.waterreminder.app
      PRODUCT_NAME: WaterReminderApp
      MARKETING_VERSION: "1.3"
      CURRENT_PROJECT_VERSION: "3"
      CODE_SIGN_STYLE: Automatic
      CODE_SIGNING_ALLOWED: true
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_INCLUDE_ALL_APPICON_ASSETS: true
      GENERATE_ASSET_SYMBOLS: true
      IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    info:
      path: Sources/Info.plist
      properties:
        CFBundleDisplayName: "Water Reminder"
        CFBundleName: "WaterReminderApp"
        CFBundlePackageType: APPL
        CFBundleShortVersionString: "1.3"
        CFBundleVersion: "3"
        UILaunchStoryboardName: LaunchScreen
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        NSUserNotificationsUsageDescription: "This app needs notification permission to remind you to drink water throughout the day."
        ITSAppUsesNonExemptEncryption: false
        LSApplicationQueriesSchemes:
          - https
        UIStatusBarStyle: UIStatusBarStyleDefault
        UIViewControllerBasedStatusBarAppearance: false
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight